### PR TITLE
change .env logic and fix remaining funds

### LINKED ISSUE #178: Revision of .env files organization for better compliance with standards
Hello,

I have noticed that the current organization of the .env files does not follow conventional standards and could be improved for better clarity and efficiency.

Details:

Here is an overview of the current organization of the .env file:

`CONST_TOKEN_ADDRESS_MAINNET=0xdf49c9f599a0a9049d97cff34d0c30e468987389
CONST_TOKEN_ADDRESS_TESTNET=0x2beF0d7531f0aaE08ADc26A0442Ba8D0516590d0
...
CONST_BEP20_ADDRESS_BUSDTESTNET=0x4CB4473Af06B844d06b5eDeF08983B2C5C61e5af`

This could potentially pose several problems:

Lack of clear separation of environments: The environment variables for the production (mainnet) and test (testnet) environments are all stored in the same .env file, which can make their management more difficult.
Information redundancy: The information about the network type (MAINNET, TESTNET) is repeated for each environment variable.
Variable naming: The names of the variables could be more explicit to indicate their usage.
Recommendations:

I suggest reviewing the organization of the .env files to improve their readability and management. This could include:

Creating separate .env files for each environment (e.g., env.local, env.testnet, env.mainnet).
Grouping together variables related to the same aspect in each .env file.
Using more descriptive variable names to clarify their usage.
This would not only make the .env files easier to read, but also facilitate their long-term maintenance.

Thank you for your attention to this matter.

### PR DESCRIPTION
**Pull request by HamdiBenK**
-Separate the .env file in 3 files '.env.local' '.env.testnet'  & '.env.mainnet'
-getting rid of different variable for testnet & prod
-remove logic and if conditions in const.js & config.js
-remove mongoConnectoin sum and juste use mongo URL to connecto to the db
-fix bug in getReamining funds api
-add ".env.example"

### CODE REVIEW

**Review by hichri-louay — APPROVED** [review]

**Review by hichri-louay — APPROVED** [review]

**Comment by ksibisamir** [comment]
Environment Variables: You have done an excellent job of managing sensitive information such as API keys, client secrets, and other configuration details by using environment variables. This is a critical practice for maintaining the security of your application. However, make sure to also have a .env.example file that outlines all the environment variables required by the application. This helps other developers understand what they need to provide to get the application running.

File: conf/config.js [hunk 1]
```diff
@@ -2,7 +2,7 @@ const { auth } = require('google-auth-library')
 const { Token } = require('graphql')
 const { environment } = require('./settings')
 
-exports.mongoConnection = () => {
+/*exports.mongoConnection = () => {
```
Comment (ksibisamir) [inline conf/config.js]: Removal of Commented Code: I've noticed that a lot of code is currently commented out, particularly around the MongoDB connection configuration and contracts. If this code is no longer necessary, I would recommend removing it to improve readability. If parts of this code are still useful for future reference, I suggest moving it into a separate reference document or saving it in commit history.

Explanation for Commented Code: If some parts of the commented code are still relevant, it would be helpful to add comments explaining why they are commented out and under what circumstances they might be uncommented.

**Review by ksibisamir — CHANGES_REQUESTED** [review]

**Review by dhiatouati — APPROVED** [review]

**Review by ksibisamir — APPROVED** [review]
